name: "Clean up events"
description: "Move any past events from current to past"
author: "Hank Mason"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: node ../../lib/filterEvents.js
